name: Build LaTeX document
on: 
 push:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
      steps:
       uses: actions/checkout@v2
        mkdir -p path/to/artifact
        echo hello > path/to/artifact/world.txt

       uses: actions/upload-artifact@v3
       with:
          name: my-artifact
          path: path/to/artifact/world.txt
