name: Build LaTeX document
on: 
 push:
    branches: [ main ]
    paths-ignore: 
      - 'main.pdf'
      - 'README.md'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
      - name: stash pdf
        run:
          mv  main.pdf $HOME # cache the file
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: commit pdf
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mv $HOME/main.pdf $(pwd) # bring it back 
          git add main.pdf
          git commit -m "Newest version"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.KEY }}
